---
title: "Shiny Application Presentation"
author: "maars-lab"
date: "2022-10-09"
output: ioslides_presentation
runtime: shiny
---

## Effects of weight on miles per gallon
In this presentation I am going to display the effects of car weight in 1000 lbs [wt] on miles per gallon [mpg]. 

On the next slide, an interactive plot is presented. Use the slider to select the weight.


## Interactive Plot
```{r dir, echo=FALSE}
library(shiny)
shinyApp(
    # Define UI for application to plot
    shinyUI(fluidPage(

    # Application title
    titlePanel("Effects of car weight [wt] on miles per gallon [mpg]"),
    
    # Sidebar with a slider input for car weight
    sidebarLayout(
            sidebarPanel(
                    sliderInput("sliderWT", "What is the weight of the car in 1000 lbs?", 1, 6, value = 3), 
                    checkboxInput("showModel1", "Show/Hide Model 1", value = TRUE), 
                    checkboxInput("showModel2", "Show/Hide Model 2", value = TRUE), 
        ),

        # Show a plot of the generated distribution
        mainPanel(
                plotOutput("carPlot"),
                h3("Predicted mpg from Model 1:"),
                textOutput("pred1"),
                h3("Predicted mpg from Model 2:"),
                textOutput("pred2")
        )
    )
)),

# Define server logic required to plot
shinyServer(function(input, output) {
        mtcars$wtif <- ifelse(mtcars$wt - 3 > 0, mtcars$wt - 3, 0) 
        model1 <- lm(mpg ~ wt, data = mtcars)
        model2 <- lm(mpg ~ wtif + wt, data = mtcars)
        
        model1pred <- reactive({
                wtInput <- input$sliderWT
                predict(model1, newdata = data.frame(wt = wtInput))
        })
        
        model2pred <- reactive({
                wtInput <- input$sliderWT
                predict(model2, newdata = data.frame(wt = wtInput,
                                                     wtif = ifelse(wtInput - 3 > 0,
                                                                   wtInput - 3, 0)))
        })

        output$carPlot <- renderPlot({
                wtInput <- input$sliderWT
                
                plot(mtcars$wt, mtcars$mpg, 
                     xlab = "weight in 1000 lbs", ylab = "miles per gallon", 
                     bty = "n", pch = 16,
                     xlim = c(1, 6), ylim = c(10, 40))
                if(input$showModel1){
                        abline(model1, col = "goldenrod", lwd = 2)
                }
                if(input$showModel2){
                        model2lines <- predict(model2, newdata = data.frame(
                                wt = 1:6, wtif = ifelse(1:6 - 3 > 0, 1:6 - 3, 0)))
                        lines(1:6, model2lines, col = "darkblue", lwd = 2)
                }

        legend(25, 250, c("Model 1 Prediction", "Model 2 Prediction"), 
               pch=16, col = c("goldenrod", "darkblue"), bty = "n", cex = 1.2)
        points(wtInput, model1pred(), col = "goldenrod", pch = 16, cex = 2) 
        points(wtInput, model2pred(), col = "darkblue", pch = 16, cex = 2)
        })
                       
        output$pred1 <- renderText({
                model1pred()
        })
        
        output$pred2 <- renderText({
                model2pred()
        })
})
)
```

## The Model explained
By selecting the car weight using the slider, the output generates a prediction of mpg from Model 1 [defined as lm(mpg ~ wt)] and a prediction of mpg from Model 2 [defined as lm(mpg ~ wtif + wt)]. The wtif in Model 2 is defined as [ifelse(wt - 3 > 0, wt - 3, 0)]. 

While in Model 1 only a linear model is used, in Model 2 a hockey-stick calculation is applied where the break-point is defined at 3000 lbs car weight. Therefore, we are able to compare the effect of weight on miles per gallon and the differences in these two models. 

## Conclusion
In conclusion, although the models differ from each other, car weight and miles per gallon have a negative correlation to each other. That means, the higher the weight [wt] the less miles per gallon [mpg] and vice versa.


